# .github/workflows/build-and-deploy.yml
name: Build and Deploy Icon Viewer

on:
  push:
    branches:
      - main # ** IMPORTANT: Change 'main' to the branch you commit icons.json to **

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # The type of machine the job runs on

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a recent, stable Node.js version

      # Step 3: Install Node.js dependencies (just for the build script)
      - name: Install dependencies
        run: npm install # This will install anything listed in your package.json

      # Step 4: Run the build script to generate the website files in ./dist
      - name: Build website
        run: npm run build # Executes the 'build' script defined in package.json

      # Step 5: Deploy the built website to GitHub Pages
      # This step uses a popular action to handle the deployment process
      - name: Deploy to GitHub Pages
        # This condition ensures deployment only happens if the previous build step succeeded
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          # Automatically provided by GitHub Actions with write permissions to the repo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The directory containing the static files to deploy (output of our build script)
          publish_dir: ./src
          # The branch GitHub Pages will serve from. 'gh-pages' is standard, but you can use 'main'
          # if your repo settings are configured to deploy from 'main' branch /docs folder.
          publish_branch: gh-pages # The branch the action will push the built site to

          # Uncomment the line below and replace with your custom domain if you are using one
          # cname: your-custom-domain.com